HRM.Web/Controllers/Table/EmployeeReportingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRM.Data.Table;
using HRM.Model.Table;
using HRM.Utility;
using HRM.Web.Controllers.Shared;
using Microsoft.Ajax.Utilities;

namespace HRM.Web.Controllers.Table
{
    public class EmployeeReportingController : HrmController
    {
        private readonly EmployeeReportingData _data = new EmployeeReportingData();
        private readonly EmployeeWorkStationUnitData _wsData = new EmployeeWorkStationUnitData();

        public EmployeeReportingController()
        {
        }

        protected EmployeeReportingController(EmployeeReportingData data)
        {
            _data = data;
        }

        #region View

        public ActionResult Index()
        {
            return View("List");
        }

        public ActionResult List()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            return View(id);
        }

        [HttpGet]
        public ActionResult Detail(long id)
        {
            return View(id);
        }

        #endregion

        #region List

        [HttpPost]
        public ContentResult Find(long pageNo, long pageSize, EmployeeReporting filter)
        {
            List<EmployeeReporting> reportings = _data.Detail.AllActiveOrInactive()
                .Include(x => x.EmployeeWorkStationUnit.Employee)
                .Include(x => x.EmployeeWorkStationUnit.WorkStationUnit.Company)
                .Include(x => x.EmployeeWorkStationUnit.WorkStationUnit.Branch)
                .Include(x => x.EmployeeWorkStationUnit.WorkStationUnit.Department)
                .Include(x => x.ParentEmployeeWorkStationUnit.Employee)
                .Include(x => x.ParentEmployeeWorkStationUnit.WorkStationUnit.Company)
                .Include(x => x.ParentEmployeeWorkStationUnit.WorkStationUnit.Branch)
                .Include(x => x.ParentEmployeeWorkStationUnit.WorkStationUnit.Department)
                .ToList();
            return JsonContent(reportings);
        }

        public JsonResult Delete(EmployeeReporting entity)
        {           
            EmployeeReporting reporting = _data.Get(entity.Id);
            SetAffectedDetail(reporting);

            _data.Remove(reporting);
            _data.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Create

        [HttpPost]
        public ContentResult GetEmployeeWorkStationUnits()
        {
            IEnumerable<EmployeeWorkStationUnit> units = _wsData.Detail.AllActive().ToList();
            return JsonContent(units);
        }

        [HttpPost]
        public JsonResult Create(EmployeeReporting entity)
        {
            SetAffectedDetail(entity);
            _data.Add(entity);
            _data.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Update
        public ContentResult Get(long id)
        {
            var reporting = _data.Detail
                .AllActiveOrInactive()
                .Where(x => x.Id == id)
                .Include(x => x.EmployeeWorkStationUnit.WorkStationUnit.Company)
                .Include(x => x.EmployeeWorkStationUnit.WorkStationUnit.Branch)
                .Include(x => x.EmployeeWorkStationUnit.WorkStationUnit.Department)
                .Include(x => x.ParentEmployeeWorkStationUnit.WorkStationUnit.Company)
                .Include(x => x.ParentEmployeeWorkStationUnit.WorkStationUnit.Branch)
                .Include(x => x.ParentEmployeeWorkStationUnit.WorkStationUnit.Department)
                .Select(x=>x).ToList().Single();
            return JsonContent(reporting);
        }

        [HttpPost]
        public JsonResult Update(EmployeeReporting entity)
        {
            SetAffectedDetail(entity);
            EmployeeReporting reporting = _data.Get(entity.Id);
            entity.MapTo(reporting);
            _data.Replace(reporting);
            _data.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Detail

        [HttpGet]
        public ContentResult GetLogs(long id)
        {
            var reportingLog = _data.Detail
                .AllLog()
                .Where(x => x.Id == id)
                .Include(x => x.EmployeeWorkStationUnitLog.EmployeeLog)
                .Include(x => x.EmployeeWorkStationUnitLog.WorkStationUnitLog.CompanyLog)
                .Include(x => x.EmployeeWorkStationUnitLog.WorkStationUnitLog.BranchLog)
                .Include(x => x.EmployeeWorkStationUnitLog.WorkStationUnitLog.DepartmentLog)
                .Include(x=>x.ParentEmployeeWorkStationUnitLog.EmployeeLog)
                .Include(x => x.ParentEmployeeWorkStationUnitLog.WorkStationUnitLog.CompanyLog)
                .Include(x => x.ParentEmployeeWorkStationUnitLog.WorkStationUnitLog.BranchLog)
                .Include(x => x.ParentEmployeeWorkStationUnitLog.WorkStationUnitLog.DepartmentLog)
                .ToList();
            return JsonContent(reportingLog);
        }

        #endregion
    }
}

HRM.Web/Views/EmployeeReporting/Create.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Create Employee Reporting";
}

<br /><br/>

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <form class="form-horizontal row-border">
        <div class="form-group">
            <label class="col-sm-3">
                Employee <br />Workstation Unit
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: employeeWorkStationUnits,
                                                        optionsText: 'fullName',
                                                        optionsValue: 'id',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: employeeWorkStationUnitId"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3">
                Parent <br />Workstation Unit
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: parentWorkStationUnits,
                                                        optionsText: 'fullName',
                                                        optionsValue: 'id',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: parentWorkStationUnitId"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Remarks
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <textarea class="form-control" placeholder="Remarks" data-bind="value:remarks"> </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Attachment Date
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <div class="input-group">
                    <input type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: attachmentDate, hasFocus: isAttachmentDateFocused" />
                    <span class="input-group-btn">
                        <button class="btn btn-warning" type="button" data-bind="click: showAttachmentDate">
                            <i class="fa fa-calendar">
                                <small style="font-weight: normal;">dd-mm-yyyy</small>
                            </i>
                        </button>
                        <button class="btn btn-success" type="button" data-bind="click: resetAttachmentDate">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Detachment Date
            </label>
            <div class="col-sm-6">
                <div class="input-group">
                    <input type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: detachmentDate, hasFocus: isDetachmentDateFocused" />
                    <span class="input-group-btn">
                        <button class="btn btn-warning" type="button" data-bind="click: showDetachmentDate">
                            <i class="fa fa-calendar">
                                <small style="font-weight: normal;">dd-mm-yyyy</small>
                            </i>
                        </button>
                        <button class="btn btn-success" type="button" data-bind="click: resetDetachmentDate">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Status
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: allStatuses,
                                                        optionsText:'name',
                                                        optionsValue:'name',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: status "></select>
            </div>
        </div>
        <br />
        <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" data-bind="click: create">
                    <i class="fa fa-plus"></i> Create
                </a>
                <a class="btn btn-info" data-bind="click: reset">
                    <i class="fa fa-refresh"></i> Reset
                </a>
            </div>
        </div>
    </form>
</div>


@section scripts
{
    <script src="@Url.Content("~/Views/EmployeeReporting/create.js")"></script>
}

HRM.Web/Views/EmployeeReporting/Detail.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Employee Reporting Log";
}

<input type="hidden" value="@(Model)" id="txtReportingId" />

<br/><br/>
<div class="box-info">
    <div class="table-responsive">
        <table class="table table-condensed table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th style="width: 7%;  text-align: center; vertical-align: top">SN</th>
                    <th style="width: 20%; text-align: center; vertical-align: top">Employee</th>
                    <th style="width: 20%; text-align: center; vertical-align: top">Reported To</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Attachment Date</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Detachment Date</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Remarks</th>
                    <th style="width: 5%; text-align: center; vertical-align: top">Status</th>
                    <th style="width: 8%; text-align: center; vertical-align: top">Affected By</th>
                    <th style="width: 13%; text-align: center; vertical-align: top">Affected DateTime</th>
                    <th style="width: 5%; text-align: center; vertical-align: top">Affect Type</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: reportingLogs">
                <tr>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: $index() + 1"></span>
                    </td>
                    <td style="text-align: left">
                        Name: <b><span class="name" data-bind="text: employeeName"></span></b><br />
                        Company: <span class="name" data-bind="text: employeeWUC"></span><br />
                        Branch: <span class="name" data-bind="text: employeeWUB"></span><br />
                        Department: <span class="name" data-bind="text: employeeWUD"></span>
                    </td>
                    <td style="text-align: left">
                        <!-- ko if: reportedName === null -->
                        <span class="name" data-bind="text: reportedName"></span><br />
                        <!-- /ko -->
                        <!-- ko if: reportedName != null -->
                        Name: <b><span class="name" data-bind="text: reportedName"></span></b><br />
                        <!-- /ko -->
                        <span class="name" data-bind="text: reportedWUC"></span><br />
                        <span class="name" data-bind="text: reportedWUB"></span><br />
                        <span class="name" data-bind="text: reportedWUD"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: attachmentDate"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: detachmentDate"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: remarks"></span>
                    </td>
                    <td>
                        <!-- ko if: status == 0 -->
                        <span class="label label-success" data-bind="text: statusString"></span>
                        <!-- /ko -->
                        <!-- ko if: status == 1 -->
                        <span class="label label-warning" data-bind="text: statusString"></span>
                        <!-- /ko -->
                    </td>
                    <td>
                        <span class="name" data-bind="text: affectedByName"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: affectedDate"></span>
                    </td>
                    <td>
                        <!-- ko if: logStatus === 0 -->
                        <span class="label label-success">Created</span>
                        <!-- /ko -->
                        <!-- ko if: logStatus === 1 -->
                        <span class="label label-warning">Updated</span>
                        <!-- /ko -->
                        <!-- ko if: logStatus === 2 -->
                        <span class="label label-danger">Deleted</span>
                        <!-- /ko -->
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


@section scripts
{
    <script src="@Url.Content("~/Views/EmployeeReporting/detail.js")"></script>
}

HRM.Web/Views/EmployeeReporting/List.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Employee Reporting Hierarchy List";
}

<a class="btn btn-success" href="@Url.Action("Create", "EmployeeReporting")">
    <i class="fa fa-plus"></i>
    Create
</a>

<a class="btn btn-primary pull-right" href="@Url.Action("Create", "EmployeeReporting")">
    <i class="fa fa-search"></i>
    Search
</a>

<br /><br />

<div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th style="width: 7%; vertical-align: top">SN</th>
                <th style="width: 18%; text-align: center; vertical-align: top">Employee</th>
                <th style="width: 18%; text-align: center; vertical-align: top">Reported To</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Attachment Date</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Detachment Date</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Remarks</th>
                <th style="width: 5%; text-align: center; vertical-align: top">Status</th>
                <th style="width: 5%; text-align: center; vertical-align: top">Actions</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: reportings">
            <tr>
                <td>
                    <span class="name" data-bind="text: $index() + 1"></span>
                </td>
                <td style="text-align: left">
                    Name: <b><span class="name" data-bind="text: employeeName"></span></b><br/>
                    Company: <span class="name" data-bind="text: employeeWUC"></span><br/>
                    Branch: <span class="name" data-bind="text: employeeWUB"></span><br/>
                    Department: <span class="name" data-bind="text: employeeWUD"></span>
                </td>
                <td style="text-align: left">
                    <!-- ko if: reportedName === null -->
                    <span class="name" data-bind="text: reportedName"></span>
                    <!-- /ko -->
                    <!-- ko if: reportedName != null -->
                    Name: <b><span class="name" data-bind="text: reportedName"></span></b>
                    <!-- /ko -->
                    <span class="name" data-bind="text: reportedWUC"></span><br />
                    <span class="name" data-bind="text: reportedWUB"></span><br />
                    <span class="name" data-bind="text: reportedWUD"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: attachmentDate"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: detachmentDate"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: remarks"></span>
                </td>
                <td>
                    <!-- ko if: status == 0 -->
                    <span class="label label-success" data-bind="text: statusString"></span>
                    <!-- /ko -->
                    <!-- ko if: status == 1 -->
                    <span class="label label-warning" data-bind="text: statusString"></span>
                    <!-- /ko -->
                </td>
                <td>
                    <div class="dropdown">
                        <button id="btnDDL" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" style="width: 5%">
                            <li><a role="menuitem" href="#" data-bind="click: $root.showDetail"><i class="fa fa-eye"></i>&nbsp; Detail</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.showToEdit"><i class="fa fa-pencil"></i>&nbsp; Update</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.confirmToDelete"><i class="fa fa-trash-o"> </i>&nbsp; Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div style="height: 30px"></div>


@section scripts{
    <script src="@Url.Content("~/Views/EmployeeReporting/list.js")"></script>
}

HRM.Web/Views/EmployeeReporting/Update.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Update Employee Reporting";
}

<input type="hidden" value="@(Model)" id="txtReportingId" />

<br /><br/>

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <form class="form-horizontal row-border">
        <div class="form-group">
            <label class="col-sm-3">
                Employee <br />Workstation Unit
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" data-bind="value: employeeWS" readonly="" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3">
                Parent <br />Workstation Unit
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" data-bind="value: parentWS" readonly="" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Remarks
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <textarea class="form-control" placeholder="Remarks" data-bind="value:remarks"> </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Attachment Date
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <div class="input-group">
                    <input type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: attachmentDate, hasFocus: isAttachmentDateFocused" />
                    <span class="input-group-btn">
                        <button class="btn btn-warning" type="button" data-bind="click: showAttachmentDate">
                            <i class="fa fa-calendar">
                                <small style="font-weight: normal;">dd-mm-yyyy</small>
                            </i>
                        </button>
                        <button class="btn btn-success" type="button" data-bind="click: resetAttachmentDate">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Detachment Date
            </label>
            <div class="col-sm-6">
                <div class="input-group">
                    <input type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: detachmentDate, hasFocus: isDetachmentDateFocused" />
                    <span class="input-group-btn">
                        <button class="btn btn-warning" type="button" data-bind="click: showDetachmentDate">
                            <i class="fa fa-calendar">
                                <small style="font-weight: normal;">dd-mm-yyyy</small>
                            </i>
                        </button>
                        <button class="btn btn-success" type="button" data-bind="click: resetDetachmentDate">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Status
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: allStatuses,
                                                        optionsText:'name',
                                                        optionsValue:'name',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: status "></select>
            </div>
        </div>
        <br />
        <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" data-bind="click: update">
                    <i class="fa fa-pencil"></i> Update
                </a>
                <a class="btn btn-info" data-bind="click: reset">
                    <i class="fa fa-refresh"></i> Reset
                </a>
            </div>
        </div>
    </form>
</div>


@section scripts
{
    <script src="@Url.Content("~/Views/EmployeeReporting/update.js")"></script>
}