HRM.Web/Controllers/BonusController.cs
using System.Web.Mvc;
using HRM.Logic;
using HRM.Model.Table;
using HRM.Web.Controllers.Shared;

namespace HRM.Web.Controllers
{
    public class BonusController : HrmController
    {
        private readonly BonusLogic _logic;

        public BonusController (): this(new BonusLogic())
        {
        }

        protected BonusController ( BonusLogic logic )
        {
            _logic = logic;
        }

        public ContentResult Get(long id)
        {
            return JsonContent(_logic.Get(id));
        }

        #region List

        public ActionResult Index()
        {
            return View("List");
        }

        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public ContentResult Find(int pageNo, int pageSize, Bonus filter)
        {
            return JsonContent(_logic.Find(pageNo, pageSize, filter));
        }

        #endregion

        #region Create

        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetBonusTypes()
        {
            return Json(_logic.GetBonusTypes(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult IsTitleUsed(string title)
        {
            return Json(_logic.HasTitleUsed(title), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(Bonus bonus)
        {
            SetAffectedDetail(bonus);
            _logic.Create(bonus);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Delete

        [HttpPost]
        public ActionResult Delete(Bonus bonus)
        {
            SetAffectedDetail(bonus);
            _logic.Remove(bonus);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Detail

        [HttpGet]
        public ActionResult Detail(long id)
        {
            return View(id);
        }

        [HttpGet]
        public ContentResult GetLogs(long id)
        {
            return JsonContent(_logic.GetLogs(id));
        }

        #endregion

        #region Update

        public ActionResult Update(long id)
        {
            return View(id);
        }

        [HttpPost]
        public JsonResult TitleUsedExceptItself(string title, long id)
        {
            return Json(_logic.HasTitleUsedExcept(title, id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(Bonus model)
        {
            SetAffectedDetail(model);
            _logic.Update(model);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

HRM.Web/Views/Bonus/Create.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Create Bonus ";
}

<h3>Bonus Info.</h3>
<hr />

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <form id="validate-form" class="form-horizontal" action="#">
        <div class="form-group">
            <label class="col-sm-3 control-label"> Title </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Bonus Title" data-bind="value: title" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label"> Bonus Type </label>
            <div class="col-sm-8">
                <select class="form-control" data-bind="options: allBonusTypes,
                                                            optionsText: 'text',
                                                            optionsValue: 'value',
                                                            optionsCaption: '--- Please Select ---',
                                                            value: bonusTypeId"></select>
            </div>
        </div> 

        <div class="form-group">
            <label class="col-sm-3 control-label"> As Percentage </label>
            <div class="col-sm-8">
                <input id="chkPercentage" type="checkbox" name="agree"  data-bind="checked: asPercentage"> 
                </div>    
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label"> Weight </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Weight" data-bind="value: weight" />
            </div> 
        </div>
        
        <div class="form-group">
            <label class="col-sm-3">  Status </label>
            <div class="col-sm-8">
                <select class="form-control" data-bind="options: allStatus,
                                                            optionsText: 'name',
                                                            optionsValue: 'name',
                                                            optionsCaption: '--- Please Select ---',
                                                            value: status"></select>
        </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" href="#" data-bind="click: create">
                    <i class="fa fa-plus"></i>
                    Create
                </a>
                <a class="btn btn-info" href="#" data-bind="click: reset">
                    <i class="fa fa-undo"></i>
                    Reset
                </a>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-2"></div>

@section scripts{
    <script src="@Url.Content("~/Views/Bonus/create.js")"></script>
}

HRM.Web/Views/Bonus/Detail.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Bonus Detail";
}

<h3>Bonus Info.</h3>
<hr />

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <input type="hidden" value="@(Model)" id="bonusId" />
        <div class="box-info">
            <form id="validation-form" class="form-horizontal" action="#" data-bind="with: bonus">
                <div class="form-group">
                    <label class="col-sm-3 ">Title</label>
                    <div class="col-sm-6">
                        <span data-bind="text:title"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 ">Bonus Type</label>
                    <div class="col-sm-6">
                        <span data-bind="text:bonusTypeName"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 ">Weight</label>
                    <div class="col-sm-6">
                        <span data-bind="text:weight"></span>
                    </div>
                </div>

            </form>
        </div>
    </div>
    <div class="col-lg-2"></div>
</div>


<h3>Bonus Log</h3>
<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-bordered table-hover">

                <thead>
                    <tr>
                        <th style="text-align: center">SN</th>
                        <th style="text-align: center">Title</th>
                        <th style="text-align: center">Bonus Type</th>
                        <th style="text-align: center">Percentage</th>
                        <th style="text-align: center">Weight</th>
                        <th style="text-align: center">Status</th>
                        <th style="text-align: center">Affected By</th>
                        <th style="text-align: center">Affected DateTime</th>
                        <th style="text-align: center">Affect Type</th>
                    </tr>
                </thead>

                <tbody data-bind="foreach: logs">
                    <tr>
                        <td>
                            <span class="name" data-bind="text: $index() + 1"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: title"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: bonusTypeName"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: asPercentage"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: weight"></span>
                        </td>
                        <td>
                            <!-- ko if: status == 0 -->
                            <span class="label label-success" data-bind="text: statusString"></span>
                            <!-- /ko -->
                            <!-- ko if: status == 1 -->
                            <span class="label label-warning" data-bind="text: statusString"></span>
                            <!-- /ko -->
                        </td>
                        <td>
                            <span class="name" data-bind="text: affectedByEmployeeName"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: affectedDate"></span>
                        </td>
                        <td>
                            <!-- ko if: logStatus === 0 -->
                            <span class="label label-success">Created</span>
                            <!-- /ko -->
                            <!-- ko if: logStatus === 1 -->
                            <span class="label label-warning">Updated</span>
                            <!-- /ko -->
                            <!-- ko if: logStatus === 2 -->
                            <span class="label label-danger">Deleted</span>
                            <!-- /ko -->
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Views/Bonus/detail.js")"></script>
}

HRM.Web/Views/Bonus/List.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Bonus List";
}

<h2>Available Bonus List</h2>

<a class="btn btn-success" href="@Url.Action("Create", "Bonus")">
    <i class="fa fa-plus"></i>
    Create
</a>
<a class="btn btn-info pull-right" href="#">
    <i class="fa fa-search"></i>
    Search
</a>

<div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered table-hover">
        <thead>
            <tr role="row">
                <th style="text-align: center">SN</th>
                <th style="text-align: center">Title</th>
                <th style="text-align: center">Bonus Type</th>
                <th style="text-align: center">As Percentage or Not</th> 
                <th style="text-align: center">Weight</th>
                <th style="text-align: center">Status</th>
                <th style="text-align: center">Actions</th>
            </tr>
        </thead>
        <tbody role="alert" aria-live="polite" aria-relevant="all" data-bind="foreach: bonuses">
            <tr>
                <td class="name" style="text-align: center" data-bind="text: $index() + 1"></td>
                <td style="text-align: center" class=" sorting_1">
                    <span class="name" data-bind="text: title"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: bonusTypeName"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: asPercentage"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: weight"></span>
                </td>
                <td style="text-align: center">
                    <!-- ko if: status == 0 -->
                    <span class="label label-success" data-bind="text: statusString"></span>
                    <!-- /ko -->
                    <!-- ko if: status == 1 -->
                    <span class="label label-warning" data-bind="text: statusString"></span>
                    <!-- /ko -->
                </td>
                <td style="text-align: left">
                    <div class="dropdown">
                        <button id="btnDDL" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a role="menuitem" href="#" data-bind="click: $root.detail"><i class="fa fa-eye"></i>&nbsp; Detail</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.update"><i class="fa fa-pencil"></i>&nbsp; Update</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.confirmDelete"><i class="fa fa-trash-o"> </i>&nbsp; Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
</table>
</div>

@section scripts
{
    <script src="@Url.Content("~/Views/Bonus/list.js")"></script>
}

HRM.Web/Views/Bonus/Update.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Update Bonus ";
}

<h3>Bonus Info.</h3>
<hr />

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <input type="hidden" value="@(Model)" id="bonusId" />
    <form id="validate-form" class="form-horizontal" action="#">
        <div class="form-group">
            <label class="col-sm-3 control-label"> Title </label>
            <div class="col-sm-8">
                <input class="form-control"  data-bind="value: title" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Bonus Type </label>
            <div class="col-sm-8">
                <select class="form-control" data-bind="options: allBonusTypes,
                                                            optionsText: 'text',
                                                            optionsValue: 'value',
                                                            optionsCaption: '--- Please Select ---',
                                                            value: bonusTypeId"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> As Percentage </label>
            <div class="col-sm-8">
                <input type="checkbox" data-bind="checked: asPercentage">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Weight </label>
            <div class="col-sm-8">
                <input class="form-control" data-bind="value: weight" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3">  Status </label>
            <div class="col-sm-8">
                <select class="form-control" data-bind="options: allStatus,
                                                            optionsText: 'name',
                                                            optionsValue: 'name',
                                                            optionsCaption: '--- Please Select ---',
                                                            value: status"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" href="#" data-bind="click: update">
                    <i class="fa fa-pencil"></i>
                    Update
                </a>
                <a class="btn btn-info" href="#" data-bind="click: reset">
                    <i class="fa fa-undo"></i>
                    Reset
                </a>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-2"></div>

@section scripts{
    <script src="@Url.Content("~/Views/Bonus/update.js")"></script>
}