HRM.Web/Controllers/EmployeeTrainingManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRM.Logic;
using HRM.Model.Table;
using HRM.Web.Controllers.Shared;

namespace HRM.Web.Controllers
{
    public class EmployeeTrainingManageController : HrmController
    {
        private readonly EmployeeTrainingManageLogic _logic;

        public EmployeeTrainingManageController() : this(new EmployeeTrainingManageLogic())
        {
        }

        protected EmployeeTrainingManageController(EmployeeTrainingManageLogic logic)
        {
            _logic = logic;
        }

        public ActionResult Index()
        {
            return View("List");
        }

        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public ContentResult Find(int pageNo, int pageSize, EmployeeTraining filter)
        {
            return JsonContent(_logic.Find(pageNo, pageSize, filter));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Create(EmployeeTraining employeeTraining)
        {
            SetAffectedDetail(employeeTraining);
            _logic.Create(employeeTraining);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(long id)
        {
            return View(id);
        }

        public ContentResult Get ( long id )
        {
            return JsonContent(_logic.Get(id));
        }

        [HttpPost]
        public JsonResult Update(EmployeeTraining model)
        {
            SetAffectedDetail(model);
            _logic.Update(model);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(EmployeeTraining employeeTraining)
        {
            SetAffectedDetail(employeeTraining);
            _logic.Remove(employeeTraining);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail ( long id )
        {
            return View(id);
        }

        public ContentResult GetLogs(long id)
        {
            return JsonContent(_logic.GetLogs(id));
        }
    }
}

HRM.Web/Views/EmployeeTrainingManage/Create.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Create Employee Training ";
}

<h3>Employee Training Info.</h3>
<hr />

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <form id="validate-form" class="form-horizontal" action="#">
        <div class="form-group">
            <label class="col-sm-3 control-label"> Title </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Training Title" data-bind="value: title" />
            </div>
        </div>   
        <div class="form-group">
            <label class="col-sm-3 control-label"> Description </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Description" data-bind="value: description" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Organized By </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Organizer" data-bind="value: organizer" />
            </div>
        </div> 
        <div class="form-group">
            <label class="col-sm-3 control-label"> Place </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Venue" data-bind="value: venue" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Trainer </label>
            <div class="col-sm-8">
                <input class="form-control" placeholder="Trainer" data-bind="value: trainer" />
            </div>
        </div> 
        <div class="form-group">
            <label class="col-sm-3 control-label"> Is Approved? </label>
            <div class="col-sm-8">
                <input id="chkPercentage" type="checkbox" name="agree" data-bind="checked: isApproved"/>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Remarks </label>
            <div class="col-sm-8">
                <textarea class="form-control" placeholder="Remarks" data-bind="value: remarks" ></textarea>
            </div>
        </div> 
        <div class="form-group">
            <label class="col-sm-3 control-label">From Date</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <input id="btnFromDate" type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: fromDate" />
                    <span class="input-group-btn">
                        <button id="btnShowFromDate" class="btn btn-warning" type="button">
                            <i class="fa fa-calendar"></i>
                            (dd-mm-yy)
                        </button>
                        <button id="btnResetFromDate" class="btn btn-success" type="button">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">TO Date</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <input id="btnToDate" type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: toDate" />
                    <span class="input-group-btn">
                        <button id="btnShowToDate" class="btn btn-warning" type="button">
                            <i class="fa fa-calendar"></i>
                            (dd-mm-yy)
                        </button>
                        <button id="btnResetToDate" class="btn btn-success" type="button">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
       <div class="form-group">
            <label class="col-sm-3">  Status </label>
            <div class="col-sm-8">
                <select class="form-control" data-bind="options: allStatus,
                                                            optionsText: 'name',
                                                            optionsValue: 'name',
                                                            optionsCaption: '--- Please Select ---',
                                                            value: status"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" href="#" data-bind="click: create">
                    <i class="fa fa-plus"></i>
                    Create
                </a>
                <a class="btn btn-info" href="#" data-bind="click: reset">
                    <i class="fa fa-undo"></i>
                    Reset
                </a>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-2"></div>

@section scripts{
    <script src="@Url.Content("~/Views/EmployeeTrainingManage/create.js")"></script>
}

HRM.Web/Views/EmployeeTrainingManage/Detail.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Employee Training Detail";
}

<h3>Employee Training Info.</h3>
<hr />

<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <input type="hidden" value="@(Model)" id="employeeTrainingId" />
        <div class="box-info">
            <form id="validation-form" class="form-horizontal" action="#" data-bind="with: employeeTraining">
                <div class="form-group">
                    <label class="col-sm-3 ">Training Title</label>
                    <div class="col-sm-6">
                        <span data-bind="text:title"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 ">Description</label>
                    <div class="col-sm-6">
                        <span data-bind="text:description"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 ">Organization</label>
                    <div class="col-sm-6">
                        <span data-bind="text:organizer"></span>
                    </div>
                </div>  
                <div class="form-group">
                    <label class="col-sm-3 ">Training Place</label>
                    <div class="col-sm-6">
                        <span data-bind="text:venue"></span>
                    </div>
                </div> 
                <div class="form-group">
                    <label class="col-sm-3 ">Training Under</label>
                    <div class="col-sm-6">
                        <span data-bind="text:trainer"></span>
                    </div>
                </div>    
                <div class="form-group">
                    <label class="col-sm-3 ">Training Start Date</label>
                    <div class="col-sm-6">
                        <span data-bind="text:fromDate"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 ">Training end Date</label>
                    <div class="col-sm-6">
                        <span data-bind="text:toDate"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 ">Comments</label>
                    <div class="col-sm-6">
                        <span data-bind="text:remarks"></span>
                    </div>
                </div>

            </form>
        </div>
    </div>
    <div class="col-lg-2"></div>
</div>   

<h3>Employee Training Log</h3>
<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th style="text-align: center">SN</th>
                        <th style="text-align: center">Title</th>
                        <th style="text-align: center">Description</th>
                        <th style="text-align: center">Organization</th>
                        <th style="text-align: center">Venue</th> 
                        <th style="text-align: center">Trainer</th>
                        <th style="text-align: center">Is Approved</th>
                        <th style="text-align: center">Remarks</th>
                        <th style="text-align: center">From Date</th>
                        <th style="text-align: center">To Date</th>
                        <th style="text-align: center">Status</th>
                        <th style="text-align: center">Affected By</th>
                        <th style="text-align: center">Affected DateTime</th>
                        <th style="text-align: center">Affect Type</th>
                    </tr>
                </thead>

                <tbody data-bind="foreach: logs">
                    <tr>
                        <td>
                            <span class="name" data-bind="text: $index() + 1"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: title"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text:description"></span>
                        </td> 
                        <td>
                            <span class="name" data-bind="text:organizer"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text:venue"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text:trainer"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text:isApproved"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: remarks"></span>
                        </td> 
                        <td>
                            <span class="name" data-bind="text: fromDate"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: toDate"></span>
                        </td>
                        <td>
                            <!-- ko if: status == 0 -->
                            <span class="label label-success" data-bind="text: statusString"></span>
                            <!-- /ko -->
                            <!-- ko if: status == 1 -->
                            <span class="label label-warning" data-bind="text: statusString"></span>
                            <!-- /ko -->
                        </td>
                        <td>
                            <span class="name" data-bind="text: affectedByEmployeeName"></span>
                        </td>
                        <td>
                            <span class="name" data-bind="text: affectedDate"></span>
                        </td>
                        <td>
                            <!-- ko if: logStatus === 0 -->
                            <span class="label label-success">Created</span>
                            <!-- /ko -->
                            <!-- ko if: logStatus === 1 -->
                            <span class="label label-warning">Updated</span>
                            <!-- /ko -->
                            <!-- ko if: logStatus === 2 -->
                            <span class="label label-danger">Deleted</span>
                            <!-- /ko -->
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Views/EmployeeTrainingManage/detail.js")"></script>
}

HRM.Web/Views/EmployeeTrainingManage/List.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Employee Training List";
}

<h2>Available Employee Training List</h2>

<a class="btn btn-success" href="@Url.Action("Create", "EmployeeTrainingManage")">
    <i class="fa fa-plus"></i>
    Create
</a>
<a class="btn btn-info pull-right" href="#">
    <i class="fa fa-search"></i>
    Search
</a>

<div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered table-hover">
        <thead>
            <tr role="row">
                <th style="text-align: center">SN</th>
                <th style="text-align: center">Title</th>
                <th style="text-align: center">Description</th>
                <th style="text-align: center">Organizer</th>
                <th style="text-align: center">Venue</th> 
                <th style="text-align: center">Trainer</th> 
                <th style="text-align: center">IsApproved</th>
                <th style="text-align: center">Remarks</th>
                <th style="text-align: center">Duration From Date</th>
                <th style="text-align: center">Duration To Date</th>
                <th style="text-align: center">Status</th>
                <th style="text-align: center">Actions</th>
            </tr>
        </thead>
        <tbody role="alert" aria-live="polite" aria-relevant="all" data-bind="foreach: employeeTrainings">
            <tr>
                <td class="name" style="text-align: center" data-bind="text: $index() + 1"></td>
                <td style="text-align: center" class=" sorting_1">
                    <span class="name" data-bind="text: title"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: description"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: organizer"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: venue"></span>
                </td> 
                <td style="text-align: center">
                    <span class="name" data-bind="text: trainer"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: isApproved"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: remarks"></span>
                </td> 
                <td style="text-align: center">
                    <span class="name" data-bind="text: durationFromDate"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: durationToDate"></span>
                </td>
                <td style="text-align: center">
                    <!-- ko if: status == 0 -->
                    <span class="label label-success" data-bind="text: statusString"></span>
                    <!-- /ko -->
                    <!-- ko if: status == 1 -->
                    <span class="label label-warning" data-bind="text: statusString"></span>
                    <!-- /ko -->
                </td>
                <td style="text-align: left">
                    <div class="dropdown">
                        <button id="btnDDL" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a role="menuitem" href="#" data-bind="click: $root.detail"><i class="fa fa-eye"></i>&nbsp; Detail</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.update"><i class="fa fa-pencil"></i>&nbsp; Update</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.confirmDelete"><i class="fa fa-trash-o"> </i>&nbsp; Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
    </table>
</div>

@section scripts
{
    <script src="@Url.Content("~/Views/EmployeeTrainingManage/list.js")"></script>
}

HRM.Web/Views/EmployeeTrainingManage/Update.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Create Employee Training ";
}

<h3>Employee Training Info.</h3>
<hr />

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <input type="hidden" value="@(Model)" id="employeeTrainingId" />   
    <form id="validate-form" class="form-horizontal" action="#">
        <div class="form-group">
            <label class="col-sm-3 control-label"> Title </label>
            <div class="col-sm-8">
                <input class="form-control"  data-bind="value: title" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Description </label>
            <div class="col-sm-8">
                <input class="form-control" data-bind="value: description" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Organized By </label>
            <div class="col-sm-8">
                <input class="form-control"  data-bind="value: organizer" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Place </label>
            <div class="col-sm-8">
                <input class="form-control" data-bind="value: venue" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Trainer </label>
            <div class="col-sm-8">
                <input class="form-control"  data-bind="value: trainer" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Is Approved? </label>
            <div class="col-sm-8">
                <input id="chkPercentage" type="checkbox" name="agree" data-bind="checked: isApproved" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"> Remarks </label>
            <div class="col-sm-8">
                <textarea class="form-control"  data-bind="value: remarks"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">From Date</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <input id="btnFromDate" type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: fromDate" />
                    <span class="input-group-btn">
                        <button id="btnShowFromDate" class="btn btn-warning" type="button">
                            <i class="fa fa-calendar"></i>
                            (dd-mm-yy)
                        </button>
                        <button id="btnResetFromDate" class="btn btn-success" type="button">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">TO Date</label>
            <div class="col-sm-8">
                <div class="input-group">
                    <input id="btnToDate" type="text" class="form-control datepicker" readonly="readonly" data-date-format="dd-mm-yyyy" data-bind="datepicker: toDate" />
                    <span class="input-group-btn">
                        <button id="btnShowToDate" class="btn btn-warning" type="button">
                            <i class="fa fa-calendar"></i>
                            (dd-mm-yy)
                        </button>
                        <button id="btnResetToDate" class="btn btn-success" type="button">
                            <i class="fa fa-refresh"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3">  Status </label>
            <div class="col-sm-8">
                <select class="form-control" data-bind="options: allStatus,
                                                            optionsText: 'name',
                                                            optionsValue: 'name',
                                                            optionsCaption: '--- Please Select ---',
                                                            value: status"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" href="#" data-bind="click: update">
                    <i class="fa fa-pencil"></i>
                    Update
                </a>
                <a class="btn btn-info" href="#" data-bind="click: reset">
                    <i class="fa fa-undo"></i>
                    Reset
                </a>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-2"></div>

@section scripts{
    <script src="@Url.Content("~/Views/EmployeeTrainingManage/update.js")"></script>
}