HRM.Web/Controllers/EmployeeManageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRM.Logic;
using HRM.Model.Table;
using HRM.Web.Controllers.Shared;

namespace HRM.Web.Controllers
{
    public class EmployeeManageController : HrmController
    {
        private readonly EmployeeManageLogic _logic;


        public EmployeeManageController() : this(new EmployeeManageLogic())
        {
        }

        protected EmployeeManageController(EmployeeManageLogic logic)
        {
            _logic = logic;
        }

        [HttpPost]
        public JsonResult Find(int pageNo, int pageSize, Employee filter)
        {
            return Json(data: _logic.Find(pageNo, pageSize, filter), behavior: JsonRequestBehavior.AllowGet);
        }

        #region List

        public ActionResult Index()
        {
            return View("List");
        }

        public ActionResult List()
        {
            return View();
        }

        #endregion

        #region Create

        [HttpGet]
        public ActionResult CreateBasic()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateAdditional(long id)
        {
            return View(id);
        }

        [HttpPost]
        public JsonResult GenerateTrackNo()
        {
            return Json(_logic.GenerateTrackNo(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult IsEmailUsed(string email)
        {
            return Json(_logic.HasEmail(email), JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Create(Employee employeeBasic)
        {
            SetAffectedDetail(employeeBasic);
            _logic.Create(employeeBasic);
            return Json(employeeBasic.Id, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Upload()
        {
            string fileName = null;
            int fileSize;

            for (int i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase file = Request.Files[i]; //Uploaded file
                fileSize = file.ContentLength;
                fileName = file.FileName;
                Stream fileContent = file.InputStream;

                //string path = Path.Combine(@"E:\HRM\HRM\HRM.Web\Uploaded Files", fileName);
                string path = Server.MapPath("~/Uploaded Files/" + fileName);
                string savedPath = @"Uploaded Files/" + fileName;

                if (CheckFileType(fileName))
                {
                    file.SaveAs(path);
                    return Json(savedPath);
                }
            }
            return Json("Error occured while uploading!!");
        }

        protected bool CheckFileType(string fileName)
        {
            string ext = Path.GetExtension(fileName);

            switch (ext.ToLower())
            {
                case (".gif"):
                {
                    return true;
                }
                case (".png"):
                {
                    return true;
                }
                case (".jpg"):
                {
                    return true;
                }
                case (".jpeg"):
                {
                    return true;
                }
                default:
                {
                    return false;
                }
            }
        }

        #endregion

        #region Delete

        [HttpPost]
        public ActionResult Delete(Employee model)
        {
            SetAffectedDetail(model);
            _logic.Delete(model);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Update

        public ContentResult Get(long id)
        {
            return JsonContent(_logic.Get(id));
        }

        [HttpPost]
        public JsonResult IsEmailUsedExceptEmployee(long id, string email)
        {
            return Json(_logic.IsEmailUsedExceptEmployee(id, email), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult UpdateBasic(long id)
        {
            return View(id);
        }

        [HttpGet]
        public ActionResult UpdateAdditional(long id)
        {
            return View(id);
        }

        [HttpPost]
        public ActionResult Update(Employee employeeBasic)
        {
            SetAffectedDetail(employeeBasic);
            _logic.Update(employeeBasic);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateAdditional(long id, Employee employeeAdditional)
        {
            SetAffectedDetail(employeeAdditional);
            _logic.UpdateAdditional(id, employeeAdditional);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Detail

        [HttpGet]
        public ActionResult Detail(long id)
        {
            return View(id);
        }

        [HttpGet]
        public ActionResult AdditionalDetail(long id)
        {
            return View(id);
        }

        public ContentResult GetLogs(long id)
        {
            return JsonContent(_logic.GetLogs(id));
        }

        #endregion
    }
}

HRM.Web/Controllers/Table/EmployeePayrollInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRM.Data.Table;
using HRM.Logic;
using HRM.Model.Table;
using HRM.Utility;
using HRM.Web.Controllers.Shared;

namespace HRM.Web.Controllers.Table
{
    public class EmployeePayrollInfoController : HrmController
    {
        private readonly EmployeePayrollInfoData _data = new EmployeePayrollInfoData();
        private readonly EmployeeData _employeeData = new EmployeeData();

        public EmployeePayrollInfoController()
        {
        }

        protected EmployeePayrollInfoController(EmployeePayrollInfoData data)
        {
            _data = data;
        }

        #region View

        public ActionResult Index()
        {
            return View("List");
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Update(long id)
        {
            return View(id);
        }

        public ActionResult Detail(long id)
        {
            return View(id);
        }

        #endregion

        #region List

        [HttpPost]
        public ContentResult Find(long pageNo, long pageSize, EmployeePayrollInfo filter)
        {
            List<EmployeePayrollInfo> payrollInfos = _data.Detail.AllActiveOrInactive().ToList();
            return JsonContent(payrollInfos);
        }

        public JsonResult Delete(EmployeePayrollInfo entity)
        {
            EmployeePayrollInfo payrollInfo = _data.Get(entity.Id);
            SetAffectedDetail(payrollInfo);

            _data.Remove(payrollInfo);
            _data.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Create

        [HttpPost]
        public JsonResult GetEmployees()
        {
            return Json(_employeeData.AllActiveOrInactive().ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(EmployeePayrollInfo entity)
        {
            SetAffectedDetail(entity);
            _data.Add(entity);
            _data.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Update

        public ContentResult Get(long id)
        {
            var payrollInfo = _data.Detail.Get(id);
            return JsonContent(payrollInfo);
        }

        [HttpPost]
        public JsonResult Update(EmployeePayrollInfo entity)
        {
            SetAffectedDetail(entity);
            EmployeePayrollInfo payroll = _data.Get(entity.Id);
            entity.MapTo(payroll);
            _data.Replace(payroll);
            _data.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Detail

        public ContentResult GetLogs(long id)
        {
            var reportingLog = _data.Detail.AllLog(id);
            return JsonContent(reportingLog);
        }

        #endregion
    }
}

HRM.Web/Views/EmployeePayrollInfo/Create.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Create Employee Payroll Info";
}

<br/><br/>

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <form class="form-horizontal row-border">
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Employee
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: employees,
                                                        optionsText: 'name',
                                                        optionsValue: 'id',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: employeeId"></select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Bank Name
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="Bank Name" data-bind="value: bankName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Bank Details
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="Details" data-bind="value: bankDetails" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Account No.
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="" data-bind="value: accountNo" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                TIN
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="" data-bind="value: tin" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Remarks
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <textarea class="form-control" placeholder="Remarks" data-bind="value:remarks"> </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Status
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: allStatuses,
                                                        optionsText:'name',
                                                        optionsValue:'name',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: status "></select>
            </div>
        </div>
        <br />
        <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" data-bind="click: create">
                    <i class="fa fa-plus"></i> Create
                </a>
                <a class="btn btn-info" data-bind="click: reset">
                    <i class="fa fa-refresh"></i> Reset
                </a>
            </div>
        </div>
    </form>
</div>


@section scripts
{
    <script src="@Url.Content("~/Views/EmployeePayrollInfo/create.js")"></script>
}

HRM.Web/Views/EmployeePayrollInfo/Detail.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Employee Payroll Info Log";
}

<input type="hidden" value="@(Model)" id="txtPayrollId" />

<br /><br />

<div class="box-info">
    <div class="table-responsive">
        <table class="table table-condensed table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th style="width: 5%;  text-align: center; vertical-align: top">SN</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Employee</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Bank</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Bank Details</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Account No</th>
                    <th style="width: 8%; text-align: center; vertical-align: top">TIN</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Remarks</th>
                    <th style="width: 5%; text-align: center; vertical-align: top">Status</th>
                    <th style="width: 8%; text-align: center; vertical-align: top">Affected By</th>
                    <th style="width: 10%; text-align: center; vertical-align: top">Affected DateTime</th>
                    <th style="width: 5%; text-align: center; vertical-align: top">Affect Type</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: payrollInfoLogs">
                <tr>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: $index() + 1"></span>
                    </td>
                    <td style="text-align: left">
                        <span class="name" data-bind="text: employeeName"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: bankName"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: bankDetails"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: accountNo"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: tin"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: remarks"></span>
                    </td>
                    <td>
                        <!-- ko if: status == 0 -->
                        <span class="label label-success" data-bind="text: statusString"></span>
                        <!-- /ko -->
                        <!-- ko if: status == 1 -->
                        <span class="label label-warning" data-bind="text: statusString"></span>
                        <!-- /ko -->
                    </td>
                    <td>
                        <span class="name" data-bind="text: affectedByName"></span>
                    </td>
                    <td style="text-align: center">
                        <span class="name" data-bind="text: affectedDate"></span>
                    </td>
                    <td>
                        <!-- ko if: logStatus === 0 -->
                        <span class="label label-success">Created</span>
                        <!-- /ko -->
                        <!-- ko if: logStatus === 1 -->
                        <span class="label label-warning">Updated</span>
                        <!-- /ko -->
                        <!-- ko if: logStatus === 2 -->
                        <span class="label label-danger">Deleted</span>
                        <!-- /ko -->
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


@section scripts
{
    <script src="@Url.Content("~/Views/EmployeePayrollInfo/detail.js")"></script>
}

HRM.Web/Views/EmployeePayrollInfo/List.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Employee Payroll Info List";
}

<a class="btn btn-success" href="@Url.Action("Create", "EmployeePayrollInfo")">
    <i class="fa fa-plus"></i>
    Create
</a>

<a class="btn btn-primary pull-right" href="@Url.Action("Create", "EmployeeManage")">
    <i class="fa fa-search"></i>
    Search
</a>

<br /><br />

<div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th style="width: 5%; vertical-align: top">SN</th>
                <th style="width: 15%; text-align: center; vertical-align: top">Employee</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Bank</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Bank Details</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Account No</th>
                <th style="width: 8%; text-align: center; vertical-align: top">TIN</th>
                <th style="width: 10%; text-align: center; vertical-align: top">Remarks</th>
                <th style="width: 5%; text-align: center; vertical-align: top">Status</th>
                <th style="width: 5%; text-align: center; vertical-align: top">Actions</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: paryrollInfos">
            <tr>
                <td>
                    <span class="name" data-bind="text: $index() + 1"></span>
                </td>
                <td style="text-align: left">
                    <span class="name" data-bind="text: employeeName"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: bankName"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: bankDetails"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: accountNo"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: tin"></span>
                </td>
                <td style="text-align: center">
                    <span class="name" data-bind="text: remarks"></span>
                </td>
                <td>
                    <!-- ko if: status == 0 -->
                    <span class="label label-success" data-bind="text: statusString"></span>
                    <!-- /ko -->
                    <!-- ko if: status == 1 -->
                    <span class="label label-warning" data-bind="text: statusString"></span>
                    <!-- /ko -->
                </td>
                <td>
                    <div class="dropdown">
                        <button id="btnDDL" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" style="width: 5%">
                            <li><a role="menuitem" href="#" data-bind="click: $root.showDetail"><i class="fa fa-eye"></i>&nbsp; Detail</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.showToEdit"><i class="fa fa-pencil"></i>&nbsp; Update</a></li>
                            <li><a role="menuitem" href="#" data-bind="click: $root.confirmToDelete"><i class="fa fa-trash-o"> </i>&nbsp; Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div style="height: 30px"></div>


@section scripts{
    <script src="@Url.Content("~/Views/EmployeePayrollInfo/list.js")"></script>
}

HRM.Web/Views/EmployeePayrollInfo/Update.cshtml
@{
    ViewBag.Title = ViewBag.PageTitle = "Update Employee Payroll Info";
}

<input type="hidden" value="@(Model)" id="txtPayrollId" />

<br /><br />

<div class="col-lg-2"></div>
<div class="col-lg-8">
    <form class="form-horizontal row-border">
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Employee
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" readonly="" data-bind="value: employeeName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Bank Name
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="Bank Name" data-bind="value: bankName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Bank Details
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="Details" data-bind="value: bankDetails" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Account No.
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="" data-bind="value: accountNo" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                TIN
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <input type="text" class="form-control" placeholder="" data-bind="value: tin" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Remarks
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <textarea class="form-control" placeholder="Remarks" data-bind="value:remarks"> </textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">
                Status
                <i class="fa fa-adjust fa-asterisk" style="vertical-align: middle; color: red; font-size: xx-small"></i>
            </label>
            <div class="col-sm-6">
                <select class="form-control" data-bind="options: allStatuses,
                                                        optionsText:'name',
                                                        optionsValue:'name',
                                                        optionsCaption: '--- Please Select ---',
                                                        value: status "></select>
            </div>
        </div>
        <br />
        <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-6 btn-toolbar">
                <a class="btn btn-success" data-bind="click: update">
                    <i class="fa fa-pencil"></i> Update
                </a>
                <a class="btn btn-info" data-bind="click: reset">
                    <i class="fa fa-refresh"></i> Reset
                </a>
            </div>
        </div>
    </form>
</div>


@section scripts
{
    <script src="@Url.Content("~/Views/EmployeePayrollInfo/update.js")"></script>
}